# Site settings
title: FSC
email: felipesc@mit.edu
description: Personal website
baseurl: ""
url: ""

# Conversion
markdown: kramdown
excerpt_separator: "\n\n"

lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Google analytics ID: Remove or use your own!
# google_analytics: UA-167467135-1
# google_analytics_4: G-02KDGRRB2T
# google_tag_manager: GTM-TZ9Z7HZ

# Pages shown in navbar
nav_pages:
  - name: publications
  - name: teaching

include:
  - .htaccess
  - _pages



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

scholar:

  last_name: Suarez Colmenares
  first_name: [Felipe]

  style: shb
  locale: en

  source: /cv/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
